sudo: false
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
addons:
  apt:
    packages:
      - zsh
before_install:
  - "cpanm -n Devel::Cover::Report::Coveralls\n"
script:
  cd .. && mkdir lib && mv yatt_lite lib/YATT && cd lib/YATT &&
  t/runtests.zsh $YATT_TRAVIS_OPTS

