sudo: false
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
addons:
  apt:
    packages:
      - zsh
before_install: 
  - cpanm -n Devel::Cover::Report::Coveralls
  - mysql -e 'create database myapp_test;'
  - perl -le 'print for @ARGV' 'dbname: myapp_test' 'dbuser: root' 'dbpass: ' > samples/.htdbpass
script:
  mkdir ../lib && ln -vnsf ../yatt_lite ../lib/YATT && cd ../lib/YATT &&
  samples/setup-all.zsh && t/runtests.zsh
