language: minimal
services: docker
env:
  - image=perl:5.30
  - image=perl:5.28
  - image=perl:5.26
  - image=perl:5.24
  - image=perl:5.22
  - image=perl:5.20
  - image=perl:5.18
  - image=perl:5.16
  - image=perl:5.14
  - image=perl:5.12
  - image=perl:5.10
before_install:
  - docker pull $image
  - docker run $image perl -V
script:
  - |
    docker run --init --rm -it -v $PWD:/run/lib/YATT -w /run/lib/YATT $image bash -c '
    set -euxo pipefail
    apt update
    apt install -y zsh
    cpanm -n App::cpm Test::Requires
    # cpm install -g Devel::Cover Devel::Cover::Report::Coveralls 
    cpm install -g --with-recommends --with-test --cpanfile=./cpanfile
    t/runtests.zsh
    echo DONE
    '
