language: minimal
services: docker
env:
  - image=perl:5.30
  - image=perl:5.28
  - image=perl:5.26
  - image=perl:5.24
  - image=perl:5.22
  - image=perl:5.20
  - image=perl:5.18
  - image=perl:5.16
before_install:
  - docker pull $image
  - docker run $image perl -V
script:
  - |
    docker run --init --rm -it -v $PWD:/run/lib/YATT -w /run/lib/YATT $image bash -c '
    set -euxo pipefail
    apt update
    curl -fsSL --compressed https://git.io/cpm > cpm
    chmod +x cpm
    cpm install -g Test::Requires
    # cpm install -g Devel::Cover Devel::Cover::Report::Coveralls 
    cpm install -g --with-recommends --with-test --cpanfile=./cpanfile
    apt install -y zsh
    t/runtests.zsh
    echo DONE
    '
