language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
before_install: 
  apt-get install zsh
  cpanm -n Devel::Cover::Report::Coveralls
script:
  mkdir ../lib && ln -vnsf ../yatt_lite ../lib/YATT && cd ../lib/YATT &&
  t/runtests.zsh -C
