language: minimal
services: docker
env:
  - image=perl:5.30
  - image=perl:5.28
  - image=perl:5.26
  - image=perl:5.24
  - image=perl:5.22
  - image=perl:5.20
  - image=perl:5.18
  - image=perl:5.16
before_install:
  - docker pull $image
  - docker run $image perl -V
script:
  - |
    docker run --init --rm -it -v $PWD:/run/lib/YATT -w /run/lib/YATT \
      -e COVERALLS_REPO_TOKEN \
      -e TRAVIS_BRANCH \
      $image bash -c '
    set -euxo pipefail
    if [[ -r .git/config ]]; then git checkout $TRAVIS_BRANCH; else echo NO GIT; fi
    curl -fsSL --compressed https://git.io/cpm > cpm
    chmod +x cpm
    ./cpm install -g Test::Requires Devel::Cover Devel::Cover::Report::Coveralls 
    ./cpm install -g --with-recommends --with-test --cpanfile=./cpanfile
    apt install -y zsh
    t/runtests.zsh
    cover -report coveralls
    echo DONE
    '
