---
abstract: 'Yet Another Template Toolkit, Lightweight rewrite.'
author:
  - "\"KOBAYASI, Hiroaki\" <hkoba@cpan.org>"
build_requires: {}
configure_requires:
  Module::Build: 0
  Module::CPANfile: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YATT-Lite
recommends:
  CGI::Session: 0
  DBD::SQLite: 0
  DBD::mysql: 0
  DBIx::Class: 0
  Email::Sender: 0
  Email::Simple: 0
  FCGI::Client: 0
  HTTP::Headers: 0
  Locale::PO: 0
  Pod::Simple::SimpleTree: 0
  YAML::Tiny: 0
requires:
  List::MoreUtils: 0
  List::Util: 0
  Plack: 0
  perl: '>= v5.10.1, != 5.17'
  version: 0.77
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.6
