---
abstract: 'Yet Another Template Toolkit, Lightweight rewrite.'
author:
  - "\"KOBAYASI, Hiroaki\" <hkoba@cpan.org>"
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YATT-Lite
provides:
  YATT::Lite:
    file: runyatt.lib/YATT/Lite.pm
    version: v0.0.2_2
  YATT::Lite::Breakpoint:
    file: runyatt.lib/YATT/Lite/Breakpoint.pm
  YATT::Lite::CGen:
    file: runyatt.lib/YATT/Lite/CGen.pm
  YATT::Lite::CGen::Perl:
    file: runyatt.lib/YATT/Lite/CGen/Perl.pm
  YATT::Lite::Connection:
    file: runyatt.lib/YATT/Lite/Connection.pm
  YATT::Lite::Constants:
    file: runyatt.lib/YATT/Lite/Constants.pm
  YATT::Lite::Core:
    file: runyatt.lib/YATT/Lite/Core.pm
  YATT::Lite::DBSchema:
    file: runyatt.lib/YATT/Lite/DBSchema.pm
  YATT::Lite::Entities:
    file: runyatt.lib/YATT/Lite/Entities.pm
  YATT::Lite::Error:
    file: runyatt.lib/YATT/Lite/Error.pm
  YATT::Lite::Factory:
    file: runyatt.lib/YATT/Lite/Factory.pm
  YATT::Lite::Inc:
    file: runyatt.lib/YATT/Lite/Inc.pm
  YATT::Lite::LRXML:
    file: runyatt.lib/YATT/Lite/LRXML.pm
  YATT::Lite::LRXML::ParseBody:
    file: runyatt.lib/YATT/Lite/LRXML/ParseBody.pm
  YATT::Lite::LRXML::ParseEntpath:
    file: runyatt.lib/YATT/Lite/LRXML/ParseEntpath.pm
  YATT::Lite::Macro:
    file: runyatt.lib/YATT/Lite/Macro.pm
  YATT::Lite::NSBuilder:
    file: runyatt.lib/YATT/Lite/NSBuilder.pm
  YATT::Lite::Object:
    file: runyatt.lib/YATT/Lite/Object.pm
  YATT::Lite::Types:
    file: runyatt.lib/YATT/Lite/Types.pm
  YATT::Lite::Types::TypeDesc:
    file: runyatt.lib/YATT/Lite/Types.pm
  YATT::Lite::Util:
    file: runyatt.lib/YATT/Lite/Util.pm
  YATT::Lite::Util::CmdLine:
    file: runyatt.lib/YATT/Lite/Util/CmdLine.pm
  YATT::Lite::Util::Enum:
    file: runyatt.lib/YATT/Lite/Util/Enum.pm
  YATT::Lite::Util::File:
    file: runyatt.lib/YATT/Lite/Util/File.pm
  YATT::Lite::VFS:
    file: runyatt.lib/YATT/Lite/VFS.pm
  YATT::Lite::VarMaker:
    file: runyatt.lib/YATT/Lite/VarMaker.pm
  YATT::Lite::VarTypes:
    file: runyatt.lib/YATT/Lite/VarTypes.pm
  YATT::Lite::VarTypes::t_delegate:
    file: runyatt.lib/YATT/Lite/VarTypes.pm
  YATT::Lite::Web::Connection:
    file: runyatt.lib/YATT/Lite/Web/Connection.pm
  YATT::Lite::Web::DirHandler:
    file: runyatt.lib/YATT/Lite/Web/DirHandler.pm
  YATT::Lite::Web::Dispatcher:
    file: runyatt.lib/YATT/Lite/Web/Dispatcher.pm
  YATT::Lite::XHF:
    file: runyatt.lib/YATT/Lite/XHF.pm
  YATT::Lite::XHFTest:
    file: runyatt.lib/YATT/Lite/XHFTest.pm
  YATT::Lite::XHFTest2:
    file: runyatt.lib/YATT/Lite/XHFTest2.pm
  YATT::Lite::XHFTest::Item:
    file: runyatt.lib/YATT/Lite/XHFTest.pm
  YATT::TestFiles:
    file: runyatt.lib/YATT/TestFiles.pm
requires:
  List::Util: 0
  Test::Differences: 0
  Test::More: 0
  perl: v5.10.1
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.2_2
