#!/usr/bin/env perl
# -*- mode: perl; coding: utf-8 -*-
use strict;
use warnings FATAL => qw/all/;
use 5.010;

use FindBin;
use File::Spec;

BEGIN {
  my @split = File::Spec->splitdir($FindBin::RealBin);
  if (@split >= 2 and [@split[-2,-1]] ~~ [qw/YATT scripts/]) {
    unshift @INC, File::Spec->catdir(@split[0 .. $#split-2]);
  }
}

use YATT::Lite;

# 

{
  my $pm = 'YATT/Lite.pm';
  my $libdir = substr($INC{$pm}, 0, -1-length($pm));

  my $prefix = "$libdir/YATT/scripts/yatt.";

  unless (@ARGV) {
    print join("\n", map {substr($_, length($prefix))} glob("$prefix*"))
      , "\n";
  } else {
  }
}
