name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.34'
          - '5.36'
          - '5.38'
          - 'latest'
          - 'threaded'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          apt-get update -y || true
          apt-get install -y zsh
          curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm > cpm
          perl ./cpm install -g Test::Requires B::Debug Devel::Cover Devel::Cover::Report::Coveralls 
          perl ./cpm install -g --show-build-log-on-failure --with-recommends --with-test
      - name: Run Tests (no coverage)
        if: ${{ !matrix.coverage }}
        run: PERL=$(which perl) ./t/runtests.zsh
      - name: Run Tests (with coverage)
        if: ${{ matrix.coverage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PERL=$(which perl) ./t/runtests.zsh -C
          cover -report coveralls t/cover_db
